services:
  - type: web
    name: policyeval-gpt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GEMINI_API_KEY
        fromService:
          name: gemini-api-key
          type: secret
      - key: HACKRX_API_KEY
        fromService:
          name: hackrx-api-key
          type: secret
